refresh_access_token:
  description: Refresh the API access token

doors_unlock:
  description: "Unlock a car defined by a vin. PIN setup required. See options dialog of the integration."
  fields:
    vin:
      description: "vin of the car"
      example: "Wxxxxxxxxxxxxxx"

doors_lock:
  description: "Lock a car defined by a vin."
  fields:
    vin:
      description: "vin of the car"
      example: "Wxxxxxxxxxxxxxx"

engine_start:
  description: "Start the engine of a car defined by a vin. PIN setup required. See options dialog of the integration."
  fields:
    vin:
      description: "vin of the car"
      example: "Wxxxxxxxxxxxxxx"

engine_stop:
  description: "Stop the engine of a car defined by a vin."
  fields:
    vin:
      description: "vin of the car"
      example: "Wxxxxxxxxxxxxxx"

preheat_start:
  description: "Start the pre-heating of a car defined by a vin."
  fields:
    vin:
      description: "vin of the car"
      example: "Wxxxxxxxxxxxxxx"

preheat_start_departure_time:
  description: "Start the pre-heating of a car defined by a vin and a given departure time."
  fields:
    vin:
      description: "vin of the car"
      example: "Wxxxxxxxxxxxxxx"
    time:
      description: "Departure time in minutes after midnight. E.g. valid value for 8 am would be 480. Value range is 0 to 1439"
      example: "480"

preheat_stop:
  description: "Stop the pre-heating of a car defined by a vin."
  fields:
    vin:
      description: "vin of the car"
      example: "Wxxxxxxxxxxxxxx"

sunroof_open:
  description: "Open the sunroof of a car defined by a vin. PIN setup required. See options dialog of the integration."
  fields:
    vin:
      description: "vin of the car"
      example: "Wxxxxxxxxxxxxxx"

sunroof_close:
  description: "Close the sunroof of a car defined by a vin."
  fields:
    vin:
      description: "vin of the car"
      example: "Wxxxxxxxxxxxxxx"

windows_open:
  description: "Open the windows of a car defined by a vin. PIN setup required. See options dialog of the integration."
  fields:
    vin:
      description: "vin of the car"
      example: "Wxxxxxxxxxxxxxx"

windows_close:
  description: "Close the windows of a car defined by a vin."
  fields:
    vin:
      description: "vin of the car"
      example: "Wxxxxxxxxxxxxxx"