refresh_access_token:
  description: Refresh the API access token

doors_unlock:
  description: "Unlock a car defined by a vin. PIN setup required. See options dialog of the integration."
  fields:
    vin:
      description: "vin of the car"
      example: "Wxxxxxxxxxxxxxx"

doors_lock:
  description: "Lock a car defined by a vin."
  fields:
    vin:
      description: "vin of the car"
      example: "Wxxxxxxxxxxxxxx"

engine_start:
  description: "Start the engine of a car defined by a vin."
  fields:
    vin:
      description: "vin of the car"
      example: "Wxxxxxxxxxxxxxx"

engine_stop:
  description: "Stop the engine of a car defined by a vin."
  fields:
    vin:
      description: "vin of the car"
      example: "Wxxxxxxxxxxxxxx"

sunroof_open:
  description: "Open the sunroof of a car defined by a vin."
  fields:
    vin:
      description: "vin of the car"
      example: "Wxxxxxxxxxxxxxx"

sunroof_close:
  description: "Close the sunroof of a car defined by a vin."
  fields:
    vin:
      description: "vin of the car"
      example: "Wxxxxxxxxxxxxxx"